spring:
  profiles:
    active: dev

---
# 개발 환경
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: 'AssetAssistantSecretKey1234567890AssetAssistantSecretKey1234567890'
  token:
    expiration-time: 3600000  # 1시간 (밀리초 단위)
  refresh-token:
    expiration-time: 604800000  # 7일 (밀리초 단위)

logging:
  level:
    kr.daeho.AssetAssistant: DEBUG
    org.springframework: INFO

---
# TODO: 운영 환경 DB 관련 정보 암호화 필요
# 운영 환경
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/asset_assistant?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "!gaion3413"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-validity-in-seconds: 86400

logging:
  level:
    kr.daeho.AssetAssistant: INFO
    org.springframework: WARN
  file:
    name: /var/log/asset-assistant/application.log
